/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuCategory = IDL.Variant({
  'Bruschetta' : IDL.Null,
  'ColdCoffee' : IDL.Null,
  'Pasta' : IDL.Null,
  'Wraps' : IDL.Null,
  'GarlicBread' : IDL.Null,
  'Other' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : MenuCategory,
  'price' : IDL.Nat,
  'vegetarian' : IDL.Bool,
});
export const ServiceType = IDL.Variant({
  'Delivery' : IDL.Null,
  'Takeaway' : IDL.Null,
  'DineIn' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'UPI' : IDL.Null,
  'Card' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'qty' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Nat,
  'menuItemId' : IDL.Nat,
});
export const OrderRequest = IDL.Record({
  'customerName' : IDL.Text,
  'deliveryAddress' : IDL.Opt(IDL.Text),
  'serviceType' : ServiceType,
  'paymentMethod' : PaymentMethod,
  'email' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Ready' : IDL.Null,
  'Preparing' : IDL.Null,
  'Received' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Opt(IDL.Text),
  'serviceType' : ServiceType,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const ReservationRequest = IDL.Record({
  'date' : IDL.Text,
  'time' : IDL.Text,
  'guestName' : IDL.Text,
  'partySize' : IDL.Nat,
  'phone' : IDL.Text,
});
export const ReservationStatus = IDL.Variant({
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Reservation = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReservationStatus,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'guestName' : IDL.Text,
  'zomatoLink' : IDL.Text,
  'partySize' : IDL.Nat,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMenuItem' : IDL.Func(
      [
        IDL.Record({
          'name' : IDL.Text,
          'description' : IDL.Text,
          'available' : IDL.Bool,
          'category' : MenuCategory,
          'price' : IDL.Nat,
          'vegetarian' : IDL.Bool,
        }),
      ],
      [MenuItem],
      [],
    ),
  'createOrder' : IDL.Func([OrderRequest], [Order], []),
  'createReservation' : IDL.Func([ReservationRequest], [Reservation], []),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [MenuCategory],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'updateMenuItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Record({
          'name' : IDL.Text,
          'description' : IDL.Text,
          'available' : IDL.Bool,
          'category' : MenuCategory,
          'price' : IDL.Nat,
          'vegetarian' : IDL.Bool,
        }),
      ],
      [IDL.Opt(MenuItem)],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [IDL.Bool], []),
  'updateReservationStatus' : IDL.Func(
      [IDL.Nat, ReservationStatus],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuCategory = IDL.Variant({
    'Bruschetta' : IDL.Null,
    'ColdCoffee' : IDL.Null,
    'Pasta' : IDL.Null,
    'Wraps' : IDL.Null,
    'GarlicBread' : IDL.Null,
    'Other' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : MenuCategory,
    'price' : IDL.Nat,
    'vegetarian' : IDL.Bool,
  });
  const ServiceType = IDL.Variant({
    'Delivery' : IDL.Null,
    'Takeaway' : IDL.Null,
    'DineIn' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'UPI' : IDL.Null, 'Card' : IDL.Null });
  const OrderItem = IDL.Record({
    'qty' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Nat,
    'menuItemId' : IDL.Nat,
  });
  const OrderRequest = IDL.Record({
    'customerName' : IDL.Text,
    'deliveryAddress' : IDL.Opt(IDL.Text),
    'serviceType' : ServiceType,
    'paymentMethod' : PaymentMethod,
    'email' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Ready' : IDL.Null,
    'Preparing' : IDL.Null,
    'Received' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Opt(IDL.Text),
    'serviceType' : ServiceType,
    'paymentMethod' : PaymentMethod,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const ReservationRequest = IDL.Record({
    'date' : IDL.Text,
    'time' : IDL.Text,
    'guestName' : IDL.Text,
    'partySize' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const ReservationStatus = IDL.Variant({
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Reservation = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReservationStatus,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'guestName' : IDL.Text,
    'zomatoLink' : IDL.Text,
    'partySize' : IDL.Nat,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addMenuItem' : IDL.Func(
        [
          IDL.Record({
            'name' : IDL.Text,
            'description' : IDL.Text,
            'available' : IDL.Bool,
            'category' : MenuCategory,
            'price' : IDL.Nat,
            'vegetarian' : IDL.Bool,
          }),
        ],
        [MenuItem],
        [],
      ),
    'createOrder' : IDL.Func([OrderRequest], [Order], []),
    'createReservation' : IDL.Func([ReservationRequest], [Reservation], []),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [MenuCategory],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'updateMenuItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Record({
            'name' : IDL.Text,
            'description' : IDL.Text,
            'available' : IDL.Bool,
            'category' : MenuCategory,
            'price' : IDL.Nat,
            'vegetarian' : IDL.Bool,
          }),
        ],
        [IDL.Opt(MenuItem)],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [IDL.Bool], []),
    'updateReservationStatus' : IDL.Func(
        [IDL.Nat, ReservationStatus],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };