/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type MenuCategory = { 'Bruschetta' : null } |
  { 'ColdCoffee' : null } |
  { 'Pasta' : null } |
  { 'Wraps' : null } |
  { 'GarlicBread' : null } |
  { 'Other' : null };
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : MenuCategory,
  'price' : bigint,
  'vegetarian' : boolean,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryAddress' : [] | [string],
  'serviceType' : ServiceType,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Timestamp,
  'email' : string,
  'totalAmount' : bigint,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'qty' : bigint,
  'name' : string,
  'price' : bigint,
  'menuItemId' : bigint,
}
export interface OrderRequest {
  'customerName' : string,
  'deliveryAddress' : [] | [string],
  'serviceType' : ServiceType,
  'paymentMethod' : PaymentMethod,
  'email' : string,
  'totalAmount' : bigint,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Ready' : null } |
  { 'Preparing' : null } |
  { 'Received' : null };
export type PaymentMethod = { 'UPI' : null } |
  { 'Card' : null };
export interface Reservation {
  'id' : bigint,
  'status' : ReservationStatus,
  'date' : string,
  'time' : string,
  'guestName' : string,
  'zomatoLink' : string,
  'partySize' : bigint,
  'phone' : string,
}
export interface ReservationRequest {
  'date' : string,
  'time' : string,
  'guestName' : string,
  'partySize' : bigint,
  'phone' : string,
}
export type ReservationStatus = { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Pending' : null };
export type ServiceType = { 'Delivery' : null } |
  { 'Takeaway' : null } |
  { 'DineIn' : null };
export type Timestamp = bigint;
export interface _SERVICE {
  'addMenuItem' : ActorMethod<
    [
      {
        'name' : string,
        'description' : string,
        'available' : boolean,
        'category' : MenuCategory,
        'price' : bigint,
        'vegetarian' : boolean,
      },
    ],
    MenuItem
  >,
  'createOrder' : ActorMethod<[OrderRequest], Order>,
  'createReservation' : ActorMethod<[ReservationRequest], Reservation>,
  'deleteMenuItem' : ActorMethod<[bigint], boolean>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getMenuItemsByCategory' : ActorMethod<[MenuCategory], Array<MenuItem>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getReservations' : ActorMethod<[], Array<Reservation>>,
  'updateMenuItem' : ActorMethod<
    [
      bigint,
      {
        'name' : string,
        'description' : string,
        'available' : boolean,
        'category' : MenuCategory,
        'price' : bigint,
        'vegetarian' : boolean,
      },
    ],
    [] | [MenuItem]
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], boolean>,
  'updateReservationStatus' : ActorMethod<[bigint, ReservationStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];