/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MenuItem {
    id: bigint;
    name: string;
    description: string;
    available: boolean;
    category: MenuCategory;
    price: bigint;
    vegetarian: boolean;
}
export type Timestamp = bigint;
export interface OrderItem {
    qty: bigint;
    name: string;
    price: bigint;
    menuItemId: bigint;
}
export interface Reservation {
    id: bigint;
    status: ReservationStatus;
    date: string;
    time: string;
    guestName: string;
    zomatoLink: string;
    partySize: bigint;
    phone: string;
}
export interface ReservationRequest {
    date: string;
    time: string;
    guestName: string;
    partySize: bigint;
    phone: string;
}
export interface Order {
    id: bigint;
    customerName: string;
    status: OrderStatus;
    deliveryAddress?: string;
    serviceType: ServiceType;
    paymentMethod: PaymentMethod;
    createdAt: Timestamp;
    email: string;
    totalAmount: bigint;
    phone: string;
    items: Array<OrderItem>;
}
export interface OrderRequest {
    customerName: string;
    deliveryAddress?: string;
    serviceType: ServiceType;
    paymentMethod: PaymentMethod;
    email: string;
    totalAmount: bigint;
    phone: string;
    items: Array<OrderItem>;
}
export enum MenuCategory {
    Bruschetta = "Bruschetta",
    ColdCoffee = "ColdCoffee",
    Pasta = "Pasta",
    Wraps = "Wraps",
    GarlicBread = "GarlicBread",
    Other = "Other"
}
export enum OrderStatus {
    Delivered = "Delivered",
    Ready = "Ready",
    Preparing = "Preparing",
    Received = "Received"
}
export enum PaymentMethod {
    UPI = "UPI",
    Card = "Card"
}
export enum ReservationStatus {
    Confirmed = "Confirmed",
    Cancelled = "Cancelled",
    Pending = "Pending"
}
export enum ServiceType {
    Delivery = "Delivery",
    Takeaway = "Takeaway",
    DineIn = "DineIn"
}
export interface backendInterface {
    addMenuItem(item: {
        name: string;
        description: string;
        available: boolean;
        category: MenuCategory;
        price: bigint;
        vegetarian: boolean;
    }): Promise<MenuItem>;
    createOrder(req: OrderRequest): Promise<Order>;
    createReservation(req: ReservationRequest): Promise<Reservation>;
    deleteMenuItem(id: bigint): Promise<boolean>;
    getMenuItems(): Promise<Array<MenuItem>>;
    getMenuItemsByCategory(category: MenuCategory): Promise<Array<MenuItem>>;
    getOrders(): Promise<Array<Order>>;
    getReservations(): Promise<Array<Reservation>>;
    updateMenuItem(id: bigint, item: {
        name: string;
        description: string;
        available: boolean;
        category: MenuCategory;
        price: bigint;
        vegetarian: boolean;
    }): Promise<MenuItem | null>;
    updateOrderStatus(id: bigint, status: OrderStatus): Promise<boolean>;
    updateReservationStatus(id: bigint, status: ReservationStatus): Promise<boolean>;
}
import type { MenuCategory as _MenuCategory, MenuItem as _MenuItem, Order as _Order, OrderItem as _OrderItem, OrderRequest as _OrderRequest, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, Reservation as _Reservation, ReservationStatus as _ReservationStatus, ServiceType as _ServiceType, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMenuItem(arg0: {
        name: string;
        description: string;
        available: boolean;
        category: MenuCategory;
        price: bigint;
        vegetarian: boolean;
    }): Promise<MenuItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(to_candid_record_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_MenuItem_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(to_candid_record_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_MenuItem_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrder(arg0: OrderRequest): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_OrderRequest_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Order_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_OrderRequest_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Order_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async createReservation(arg0: ReservationRequest): Promise<Reservation> {
        if (this.processError) {
            try {
                const result = await this.actor.createReservation(arg0);
                return from_candid_Reservation_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReservation(arg0);
            return from_candid_Reservation_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMenuItem(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0);
            return result;
        }
    }
    async getMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItems();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItems();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItemsByCategory(arg0: MenuCategory): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItemsByCategory(to_candid_MenuCategory_n2(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItemsByCategory(to_candid_MenuCategory_n2(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReservations(): Promise<Array<Reservation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReservations();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReservations();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMenuItem(arg0: bigint, arg1: {
        name: string;
        description: string;
        available: boolean;
        category: MenuCategory;
        price: bigint;
        vegetarian: boolean;
    }): Promise<MenuItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, to_candid_record_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, to_candid_record_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateReservationStatus(arg0: bigint, arg1: ReservationStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReservationStatus(arg0, to_candid_ReservationStatus_n33(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReservationStatus(arg0, to_candid_ReservationStatus_n33(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_MenuCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuCategory): MenuCategory {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_MenuItem_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): MenuItem {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ReservationStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReservationStatus): ReservationStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Reservation_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reservation): Reservation {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuItem]): MenuItem | null {
    return value.length === 0 ? null : from_candid_MenuItem_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: _OrderStatus;
    deliveryAddress: [] | [string];
    serviceType: _ServiceType;
    paymentMethod: _PaymentMethod;
    createdAt: _Timestamp;
    email: string;
    totalAmount: bigint;
    phone: string;
    items: Array<_OrderItem>;
}): {
    id: bigint;
    customerName: string;
    status: OrderStatus;
    deliveryAddress?: string;
    serviceType: ServiceType;
    paymentMethod: PaymentMethod;
    createdAt: Timestamp;
    email: string;
    totalAmount: bigint;
    phone: string;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n16(_uploadFile, _downloadFile, value.status),
        deliveryAddress: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.deliveryAddress)),
        serviceType: from_candid_ServiceType_n19(_uploadFile, _downloadFile, value.serviceType),
        paymentMethod: from_candid_PaymentMethod_n21(_uploadFile, _downloadFile, value.paymentMethod),
        createdAt: value.createdAt,
        email: value.email,
        totalAmount: value.totalAmount,
        phone: value.phone,
        items: value.items
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ReservationStatus;
    date: string;
    time: string;
    guestName: string;
    zomatoLink: string;
    partySize: bigint;
    phone: string;
}): {
    id: bigint;
    status: ReservationStatus;
    date: string;
    time: string;
    guestName: string;
    zomatoLink: string;
    partySize: bigint;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_ReservationStatus_n25(_uploadFile, _downloadFile, value.status),
        date: value.date,
        time: value.time,
        guestName: value.guestName,
        zomatoLink: value.zomatoLink,
        partySize: value.partySize,
        phone: value.phone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    available: boolean;
    category: _MenuCategory;
    price: bigint;
    vegetarian: boolean;
}): {
    id: bigint;
    name: string;
    description: string;
    available: boolean;
    category: MenuCategory;
    price: bigint;
    vegetarian: boolean;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        available: value.available,
        category: from_candid_MenuCategory_n6(_uploadFile, _downloadFile, value.category),
        price: value.price,
        vegetarian: value.vegetarian
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Delivered: null;
} | {
    Ready: null;
} | {
    Preparing: null;
} | {
    Received: null;
}): OrderStatus {
    return "Delivered" in value ? OrderStatus.Delivered : "Ready" in value ? OrderStatus.Ready : "Preparing" in value ? OrderStatus.Preparing : "Received" in value ? OrderStatus.Received : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Delivery: null;
} | {
    Takeaway: null;
} | {
    DineIn: null;
}): ServiceType {
    return "Delivery" in value ? ServiceType.Delivery : "Takeaway" in value ? ServiceType.Takeaway : "DineIn" in value ? ServiceType.DineIn : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UPI: null;
} | {
    Card: null;
}): PaymentMethod {
    return "UPI" in value ? PaymentMethod.UPI : "Card" in value ? PaymentMethod.Card : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Pending: null;
}): ReservationStatus {
    return "Confirmed" in value ? ReservationStatus.Confirmed : "Cancelled" in value ? ReservationStatus.Cancelled : "Pending" in value ? ReservationStatus.Pending : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Bruschetta: null;
} | {
    ColdCoffee: null;
} | {
    Pasta: null;
} | {
    Wraps: null;
} | {
    GarlicBread: null;
} | {
    Other: null;
}): MenuCategory {
    return "Bruschetta" in value ? MenuCategory.Bruschetta : "ColdCoffee" in value ? MenuCategory.ColdCoffee : "Pasta" in value ? MenuCategory.Pasta : "Wraps" in value ? MenuCategory.Wraps : "GarlicBread" in value ? MenuCategory.GarlicBread : "Other" in value ? MenuCategory.Other : value;
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Array<MenuItem> {
    return value.map((x)=>from_candid_MenuItem_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reservation>): Array<Reservation> {
    return value.map((x)=>from_candid_Reservation_n23(_uploadFile, _downloadFile, x));
}
function to_candid_MenuCategory_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuCategory): _MenuCategory {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_OrderRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderRequest): _OrderRequest {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ReservationStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReservationStatus): _ReservationStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_record_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    available: boolean;
    category: MenuCategory;
    price: bigint;
    vegetarian: boolean;
}): {
    name: string;
    description: string;
    available: boolean;
    category: _MenuCategory;
    price: bigint;
    vegetarian: boolean;
} {
    return {
        name: value.name,
        description: value.description,
        available: value.available,
        category: to_candid_MenuCategory_n2(_uploadFile, _downloadFile, value.category),
        price: value.price,
        vegetarian: value.vegetarian
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    deliveryAddress?: string;
    serviceType: ServiceType;
    paymentMethod: PaymentMethod;
    email: string;
    totalAmount: bigint;
    phone: string;
    items: Array<OrderItem>;
}): {
    customerName: string;
    deliveryAddress: [] | [string];
    serviceType: _ServiceType;
    paymentMethod: _PaymentMethod;
    email: string;
    totalAmount: bigint;
    phone: string;
    items: Array<_OrderItem>;
} {
    return {
        customerName: value.customerName,
        deliveryAddress: value.deliveryAddress ? candid_some(value.deliveryAddress) : candid_none(),
        serviceType: to_candid_ServiceType_n10(_uploadFile, _downloadFile, value.serviceType),
        paymentMethod: to_candid_PaymentMethod_n12(_uploadFile, _downloadFile, value.paymentMethod),
        email: value.email,
        totalAmount: value.totalAmount,
        phone: value.phone,
        items: value.items
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    Delivery: null;
} | {
    Takeaway: null;
} | {
    DineIn: null;
} {
    return value == ServiceType.Delivery ? {
        Delivery: null
    } : value == ServiceType.Takeaway ? {
        Takeaway: null
    } : value == ServiceType.DineIn ? {
        DineIn: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    UPI: null;
} | {
    Card: null;
} {
    return value == PaymentMethod.UPI ? {
        UPI: null
    } : value == PaymentMethod.Card ? {
        Card: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuCategory): {
    Bruschetta: null;
} | {
    ColdCoffee: null;
} | {
    Pasta: null;
} | {
    Wraps: null;
} | {
    GarlicBread: null;
} | {
    Other: null;
} {
    return value == MenuCategory.Bruschetta ? {
        Bruschetta: null
    } : value == MenuCategory.ColdCoffee ? {
        ColdCoffee: null
    } : value == MenuCategory.Pasta ? {
        Pasta: null
    } : value == MenuCategory.Wraps ? {
        Wraps: null
    } : value == MenuCategory.GarlicBread ? {
        GarlicBread: null
    } : value == MenuCategory.Other ? {
        Other: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    Delivered: null;
} | {
    Ready: null;
} | {
    Preparing: null;
} | {
    Received: null;
} {
    return value == OrderStatus.Delivered ? {
        Delivered: null
    } : value == OrderStatus.Ready ? {
        Ready: null
    } : value == OrderStatus.Preparing ? {
        Preparing: null
    } : value == OrderStatus.Received ? {
        Received: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReservationStatus): {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Pending: null;
} {
    return value == ReservationStatus.Confirmed ? {
        Confirmed: null
    } : value == ReservationStatus.Cancelled ? {
        Cancelled: null
    } : value == ReservationStatus.Pending ? {
        Pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
