/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as FoodFoodIdImport } from "./routes/food.$foodId";
import { Route as GalleryImport } from "./routes/gallery";
import { Route as IndexImport } from "./routes/index";
import { Route as MenuImport } from "./routes/menu";
import { Route as OrdersImport } from "./routes/orders";
import { Route as ReservationsImport } from "./routes/reservations";
import { Route as ReviewsImport } from "./routes/reviews";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as never);

const MenuRoute = MenuImport.update({
  id: "/menu",
  path: "/menu",
  getParentRoute: () => rootRoute,
} as never);

const OrdersRoute = OrdersImport.update({
  id: "/orders",
  path: "/orders",
  getParentRoute: () => rootRoute,
} as never);

const ReservationsRoute = ReservationsImport.update({
  id: "/reservations",
  path: "/reservations",
  getParentRoute: () => rootRoute,
} as never);

const GalleryRoute = GalleryImport.update({
  id: "/gallery",
  path: "/gallery",
  getParentRoute: () => rootRoute,
} as never);

const ReviewsRoute = ReviewsImport.update({
  id: "/reviews",
  path: "/reviews",
  getParentRoute: () => rootRoute,
} as never);

const FoodFoodIdRoute = FoodFoodIdImport.update({
  id: "/food/$foodId",
  path: "/food/$foodId",
  getParentRoute: () => rootRoute,
} as never);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/menu": {
      id: "/menu";
      path: "/menu";
      fullPath: "/menu";
      preLoaderRoute: typeof MenuImport;
      parentRoute: typeof rootRoute;
    };
    "/orders": {
      id: "/orders";
      path: "/orders";
      fullPath: "/orders";
      preLoaderRoute: typeof OrdersImport;
      parentRoute: typeof rootRoute;
    };
    "/reservations": {
      id: "/reservations";
      path: "/reservations";
      fullPath: "/reservations";
      preLoaderRoute: typeof ReservationsImport;
      parentRoute: typeof rootRoute;
    };
    "/gallery": {
      id: "/gallery";
      path: "/gallery";
      fullPath: "/gallery";
      preLoaderRoute: typeof GalleryImport;
      parentRoute: typeof rootRoute;
    };
    "/reviews": {
      id: "/reviews";
      path: "/reviews";
      fullPath: "/reviews";
      preLoaderRoute: typeof ReviewsImport;
      parentRoute: typeof rootRoute;
    };
    "/food/$foodId": {
      id: "/food/$foodId";
      path: "/food/$foodId";
      fullPath: "/food/$foodId";
      preLoaderRoute: typeof FoodFoodIdImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/menu": typeof MenuRoute;
  "/orders": typeof OrdersRoute;
  "/reservations": typeof ReservationsRoute;
  "/gallery": typeof GalleryRoute;
  "/reviews": typeof ReviewsRoute;
  "/food/$foodId": typeof FoodFoodIdRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/menu": typeof MenuRoute;
  "/orders": typeof OrdersRoute;
  "/reservations": typeof ReservationsRoute;
  "/gallery": typeof GalleryRoute;
  "/reviews": typeof ReviewsRoute;
  "/food/$foodId": typeof FoodFoodIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/menu": typeof MenuRoute;
  "/orders": typeof OrdersRoute;
  "/reservations": typeof ReservationsRoute;
  "/gallery": typeof GalleryRoute;
  "/reviews": typeof ReviewsRoute;
  "/food/$foodId": typeof FoodFoodIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/menu"
    | "/orders"
    | "/reservations"
    | "/gallery"
    | "/reviews"
    | "/food/$foodId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/menu"
    | "/orders"
    | "/reservations"
    | "/gallery"
    | "/reviews"
    | "/food/$foodId";
  id:
    | "__root__"
    | "/"
    | "/menu"
    | "/orders"
    | "/reservations"
    | "/gallery"
    | "/reviews"
    | "/food/$foodId";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  MenuRoute: typeof MenuRoute;
  OrdersRoute: typeof OrdersRoute;
  ReservationsRoute: typeof ReservationsRoute;
  GalleryRoute: typeof GalleryRoute;
  ReviewsRoute: typeof ReviewsRoute;
  FoodFoodIdRoute: typeof FoodFoodIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRoute,
  ReservationsRoute: ReservationsRoute,
  GalleryRoute: GalleryRoute,
  ReviewsRoute: ReviewsRoute,
  FoodFoodIdRoute: FoodFoodIdRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
